#!/usr/bin/perl

# File generated by menutray v0.47

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/alexis/.config/menutray/schema.pl' instead!

use utf8;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $item->signal_connect('activate', sub {system "xterm &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/ &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Accessories");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("About\ Xfce");
    $app->signal_connect('activate', sub {system "xfce4\-about &"});
    $app->set_property('tooltip_text', "Information\ about\ the\ Xfce\ Desktop\ Environment");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-about",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Adie");
    $app->signal_connect('activate', sub {system "adie &"});
    $app->set_property('tooltip_text', "Fast\ and\ convenient\ programming\ text\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("adie",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Archive\ Manager");
    $app->signal_connect('activate', sub {system "file\-roller &"});
    $app->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app->set_image('Gtk2::Image'->new_from_icon_name("file\-roller",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "electron\ \-\-app\=\/usr\/lib\/atom &"});
    $app->set_property('tooltip_text', "A\ hackable\ text\ editor\ for\ the\ 21st\ Century");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Character\ Map");
    $app->signal_connect('activate', sub {system "gucharmap &"});
    $app->set_property('tooltip_text', "Insert\ special\ characters\ into\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("accessories\-character\-map",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("compton");
    $app->signal_connect('activate', sub {system "compton\ \-\-xrender\-sync\-fence &"});
    $app->set_property('tooltip_text', "Compositor\ for\ X11");
    $app->set_image('Gtk2::Image'->new_from_icon_name("compton",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("emelFM2");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/emelfm2 &"});
    $app->set_property('tooltip_text', "2\-pane\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("emelfm2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("emelFM2");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/emelfm2 &"});
    $app->set_property('tooltip_text', "2\-pane\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("emelfm2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system\ and\ manage\ the\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Font\ Manager");
    $app->signal_connect('activate', sub {system "font\-manager &"});
    $app->set_property('tooltip_text', "Preview\,\ Compare\ and\ Manage\ Fonts");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-font",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Font\ Viewer");
    $app->signal_connect('activate', sub {system "\/usr\/libexec\/font\-manager\/font\-viewer &"});
    $app->set_property('tooltip_text', "Full\ featured\ font\ file\ preview\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-font",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FOX\ Calculator");
    $app->signal_connect('activate', sub {system "calculator &"});
    $app->set_property('tooltip_text', "Simple\ desktop\ calculator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("calculator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sakura");
    $app->signal_connect('activate', sub {system "sakura &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminal\-tango",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SpaceFM");
    $app->signal_connect('activate', sub {system "spacefm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spacefm",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SpaceFM\ File\ Search");
    $app->signal_connect('activate', sub {system "spacefm\ \-\-find\-files &"});
    $app->set_property('tooltip_text', "Search\ for\ files\ and\ folders");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spacefm\-find",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminator");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Multiple\ terminals\ in\ one\ window");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Text\ Editor");
    $app->signal_connect('activate', sub {system "gedit &"});
    $app->set_property('tooltip_text', "Edit\ text\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gedit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfi");
    $app->signal_connect('activate', sub {system "xfi &"});
    $app->set_property('tooltip_text', "A\ simple\ image\ viewer\ for\ Xfe");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfi",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfp");
    $app->signal_connect('activate', sub {system "xfp &"});
    $app->set_property('tooltip_text', "A\ simple\ package\ manager\ for\ Xfe");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfw");
    $app->signal_connect('activate', sub {system "xfw &"});
    $app->set_property('tooltip_text', "A\ simple\ text\ editor\ for\ Xfe");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfw",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Development");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "electron\ \-\-app\=\/usr\/lib\/atom &"});
    $app->set_property('tooltip_text', "A\ hackable\ text\ editor\ for\ the\ 21st\ Century");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("DBeaver");
    $app->signal_connect('activate', sub {system "\/opt\/dbeaver\/dbeaver &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("dbeaver",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Diffuse\ Merge\ Tool");
    $app->signal_connect('activate', sub {system "diffuse\ \-s &"});
    $app->set_property('tooltip_text', "Graphical\ tool\ for\ merging\ and\ comparing\ text\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("diffuse",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Electron");
    $app->signal_connect('activate', sub {system "electron &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("electron",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Emacs");
    $app->signal_connect('activate', sub {system "emacs &"});
    $app->set_property('tooltip_text', "Edit\ text");
    $app->set_image('Gtk2::Image'->new_from_icon_name("emacs",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Geany");
    $app->signal_connect('activate', sub {system "geany &"});
    $app->set_property('tooltip_text', "A\ fast\ and\ lightweight\ IDE\ using\ GTK\+");
    $app->set_image('Gtk2::Image'->new_from_icon_name("geany",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Meld");
    $app->signal_connect('activate', sub {system "meld &"});
    $app->set_property('tooltip_text', "Compare\ and\ merge\ your\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("meld",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("OpenJDK\ 1\.7\.0\ Policy\ Tool");
    $app->signal_connect('activate', sub {system "_BINDIR_\/policytool &"});
    $app->set_property('tooltip_text', "Manage\ OpenJDK\ policy\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("java\-1\.7\.0",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("pgAdmin\ III");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/pgadmin3 &"});
    $app->set_property('tooltip_text', "PostgreSQL\ Tools");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pgadmin3\/pgAdmin3\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sublime\ Text\ 3\ Dev");
    $app->signal_connect('activate', sub {system "subl3 &"});
    $app->set_property('tooltip_text', "Sophisticated\ text\ editor\ for\ code\,\ markup\ and\ prose");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sublime\-text",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Graphics");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Font\ Manager");
    $app->signal_connect('activate', sub {system "font\-manager &"});
    $app->set_property('tooltip_text', "Preview\,\ Compare\ and\ Manage\ Fonts");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-font",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Font\ Viewer");
    $app->signal_connect('activate', sub {system "\/usr\/libexec\/font\-manager\/font\-viewer &"});
    $app->set_property('tooltip_text', "Full\ featured\ font\ file\ preview\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-font",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Google\ Play\ Music\ Desktop\ Player");
    $app->signal_connect('activate', sub {system "gpmdp &"});
    $app->set_property('tooltip_text', "An\ electron\ wrapper\ for\ Google\ Play\ Music");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gpmdp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mopidy");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'mopidy\' &"});
    $app->set_property('tooltip_text', "Music\ server\ with\ support\ for\ MPD\ and\ HTTP\ clients");
    $app->set_image('Gtk2::Image'->new_from_icon_name("audio\-x\-generic",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Network");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ELinks");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'\/usr\/bin\/elinks\' &"});
    $app->set_property('tooltip_text', "Browse\ the\ World\ Wide\ Web\ in\ Text\-Mode");
    $app->set_image('Gtk2::Image'->new_from_icon_name("html",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firefox");
    $app->signal_connect('activate', sub {system "firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firefox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap");
    $app->signal_connect('activate', sub {system "zenmap &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap\ \(as\ root\)");
    $app->signal_connect('activate', sub {system "\/usr\/share\/zenmap\/su\-to\-zenmap\.sh &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Settings");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Adobe\ Flash\ Player");
    $app->signal_connect('activate', sub {system "flash\-player\-properties &"});
    $app->set_property('tooltip_text', "Preferences\ for\ Adobe\ Flash\ Player");
    $app->set_image('Gtk2::Image'->new_from_icon_name("flash\-player\-properties",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ARandR");
    $app->signal_connect('activate', sub {system "arandr &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Desktop\ Preferences");
    $app->signal_connect('activate', sub {system "pcmanfm\ \-\-desktop\-pref &"});
    $app->set_property('tooltip_text', "Change\ desktop\ wallpapers\ and\ behavior\ of\ desktop\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("user\-desktop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FOX\ Desktop\ Setup");
    $app->signal_connect('activate', sub {system "ControlPanel &"});
    $app->set_property('tooltip_text', "Setup\ desktop\ appearance\ for\ FOX\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ControlPanel",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("NVIDIA\ X\ Server\ Settings");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/nvidia\-settings &"});
    $app->set_property('tooltip_text', "Configure\ NVIDIA\ X\ Server\ Settings");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/doc\/NVIDIA_GLX\-1\.0\/nvidia\-settings\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app->signal_connect('activate', sub {system "libfm\-pref\-apps &"});
    $app->set_property('tooltip_text', "Select\ applications\ called\ on\ click\ on\ Web\ link\ or\ e\-mail\ address");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("System");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("emelFM2");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/emelfm2 &"});
    $app->set_property('tooltip_text', "2\-pane\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("emelfm2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system\ and\ manage\ the\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Htop");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LSHW");
    $app->signal_connect('activate', sub {system "\/usr\/sbin\/gtk\-lshw &"});
    $app->set_property('tooltip_text', "HardWare\ LiSter");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/lshw\/artwork\/logo\.svg",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PathFinder");
    $app->signal_connect('activate', sub {system "PathFinder &"});
    $app->set_property('tooltip_text', "File\ browser");
    $app->set_image('Gtk2::Image'->new_from_icon_name("PathFinder",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ranger");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sakura");
    $app->signal_connect('activate', sub {system "sakura &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminal\-tango",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SpaceFM");
    $app->signal_connect('activate', sub {system "spacefm &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spacefm",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminator");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Multiple\ terminals\ in\ one\ window");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Termite");
    $app->signal_connect('activate', sub {system "termite &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("UXTerm");
    $app->signal_connect('activate', sub {system "uxterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfce\ Terminal");
    $app->signal_connect('activate', sub {system "xfce4\-terminal &"});
    $app->set_property('tooltip_text', "Terminal\ Emulator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfe");
    $app->signal_connect('activate', sub {system "xfe &"});
    $app->set_property('tooltip_text', "A\ lightweight\ file\ manager\ for\ X\ Window");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfe",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("XTerm");
    $app->signal_connect('activate', sub {system "xterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Menutray");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Config");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Menu");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Schema");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/alexis\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
